version: '3.9'
services:
  prism:
    image: stoplight/prism:4
    #command: 'mock -h 0.0.0.0 /tmp/api.oas3.yml'
    command: 'mock -h 0.0.0.0 /tmp/openapi.yml'
    volumes:
      #- ./api.oas3.yml:/tmp/api.oas3.yml:ro
      - ./openapi/openapi.yaml:/tmp/openapi.yml
    ports:
      # Serve the mocked API locally as available on port 8080
      - '8090:4010'